[package]
name = "bevy_mesh_terrain_editor"
version = "0.13.0"
edition = "2021"


[dependencies]
bevy = "0.13.0"
bevy_egui = "0.25.0"
bevy_mesh_terrain = { path = "../bevy_mesh_terrain" }


bevy_mod_picking = {version="0.17.0", features=["backend_raycast",  "highlight","selection"]}
bevy_mod_raycast = "0.17.0"
seldom_fn_plugin = "0.6.0"

[[example]]
name = "raycasting"
path = "examples/raycasting.rs"

[profile.dev.package."*"]
opt-level = 3