type = "StandardMaterial"


[material]
base_color_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon.png"
normal_map_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon_normal.png"
perceptual_roughness= 0.9
base_color={ LinearRgba = [0.16, 0.25, 0.25, 1.0] }

[properties]
uv_scale_factor= 1.0 



[properties.texture_subset_dimensions]
offset= [256,  112 ]
dimensions= [32,32]
base_texture_dimensions= [352,272]
 
